INSERT INTO monarch (name, year_of_birth, year_of_death, year_of_reign_start, year_of_reign_end) VALUES ('Elizabeth II', 1926, 2022, 1952, 2022);
INSERT INTO monarch (name, year_of_birth, year_of_death, year_of_reign_start, year_of_reign_end) VALUES ('Charles III', 1948, null, 2022, null);

INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (1, 'Winston Churchill', 1874, 1965, 1951, 1955, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (2, 'Anthony Eden', 1897, 1977, 1955, 1957, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (3, 'Harold Macmillan', 1894, 1986, 1957, 1963, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (4, 'Alec Douglas-Home', 1903, 1995, 1963, 1964, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (5, 'Harold Wilson', 1916, 1995, 1964, 1970, 'Labour');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (6, 'Edward Heath', 1916, 2005, 1970, 1974, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (7, 'Harold Wilson', 1916, 1995, 1964, 1970, 'Labour');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (8, 'James Callaghan', 1912, 2005, 1976, 1979, 'Labour');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (9, 'Margaret Thatcher', 1925, 2013, 1979, 1990, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (10, 'John Major', 1943, null, 1990, 1997, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (11, 'Tony Blair', 1953, null, 1997, 2007, 'Labour');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (12, 'Gordon Brown', 1951, null, 2007, 2010, 'Labour');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (13, 'David Cameron', 1966, null, 2010, 2016, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (14, 'Theresa May', 1956, null, 2016, 2019, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (15, 'Boris Johnson', 1964, null, 2019, 2022, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (16, 'Liz Truss', 1975, null, 2022, 2023, 'Conservative');
INSERT INTO prime_minister (id, name, year_of_birth, year_of_death, year_start_office, year_out_office, party) VALUES (17, 'Rishi Sunak', 1980, null, 2022, null, 'Conservative');